# Generated by Django 5.1.1 on 2024-11-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='cart',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='product',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
